pub const DEFAULT_CAPTIAL_REP_WEIGHT: u8 = 1;
pub const DEFAULT_CONTRIBUTION_REP_WEIGHT: u8 = 1;

pub const MIN_REP_TO_CREATE_PROPOSAL: u64 = 1;
pub const MIN_REP_TO_SERVICE_PROPOSAL: u64 = 1;

pub const POINTS_PER_SECOND: u32 = 10;
pub const POINTS_DECIMAL: u32 = 1000000000;

pub const DEFAULT_PROPOSAL_VOTE_WEIGHT: u8 = 1;
pub const DEFAULT_PROPOSAL_SERVICED_WEIGHT: u8 = 8;
pub const DEFAULT_PROPOSAL_CREATED_WEIGHT: u8 = 5;

pub const DEFAULT_COUNCIL_THRESHOLD : u8 = 70;